# This file was generated by GoReleaser. DO NOT EDIT.
cask "ntee" do
  version "0.3.1"

  on_macos do
    sha256 "1dd4700226e367f6ae69bd2d98175b9a8e16d8030946b594207b50b3cfc9be95"
    url "https://github.com/nickooan/ntee-editor/releases/download/v#{version}/ntee_#{version}_darwin_all.tar.gz"
  end

  name "ntee"
  desc "Terminal text editor with LSP, git diff review, and conflict solving"
  homepage "https://github.com/nickooan/ntee-editor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ntee"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ntee"]
    end
  end

  # No zap stanza required

end
