# This file was generated by GoReleaser. DO NOT EDIT.
cask "nteedb-server" do
  version "0.5.0"

  on_macos do
    sha256 "9f5d4b9a2a3a4a72fa369dcfd47c150b6f3baa701624f2b1b6a2f8f176248ccd"
    url "https://github.com/nickooan/ntee-db/releases/download/v#{version}/nteedb-server_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "d1ace7a154f29660d9a90060e9f8e4f445665e60baa3fa836c26b899dda93b89"
      url "https://github.com/nickooan/ntee-db/releases/download/v#{version}/nteedb-server_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "21f6f22e9af822716580024fe45bdc1afa0d6cf0ed4181813bdb8863dc19dc9d"
      url "https://github.com/nickooan/ntee-db/releases/download/v#{version}/nteedb-server_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nteedb-server"
  desc "Native ntee-db server with a memcached-style text protocol"
  homepage "https://github.com/nickooan/ntee-db"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nteedb-server"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nteedb-server"]
    end
  end

  # No zap stanza required

end
