# This file was generated by GoReleaser. DO NOT EDIT.
cask "nteedb-server" do
  version "0.4.0"

  on_macos do
    sha256 "529015f9d183d5580d34f1b8da6f31453ccce63f99df34a74bf40daa99587d1f"
    url "https://github.com/nickooan/ntee-db/releases/download/v#{version}/nteedb-server_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "af826a78079ff9b75a8abf133e92826b88d3ee59384f6e985d283b59c77ad3e4"
      url "https://github.com/nickooan/ntee-db/releases/download/v#{version}/nteedb-server_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "af3081ff9af8ef044ad3af56a7679e5b12085973a823599e26029fc504ca1da2"
      url "https://github.com/nickooan/ntee-db/releases/download/v#{version}/nteedb-server_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nteedb-server"
  desc "Native ntee-db server with a memcached-style text protocol"
  homepage "https://github.com/nickooan/ntee-db"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nteedb-server"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nteedb-server"]
    end
  end

  # No zap stanza required

end
