# This file was generated by GoReleaser. DO NOT EDIT.
cask "nteedb-server" do
  version "0.3.0"

  on_macos do
    sha256 "e1e5e4674b0230dc965a6547595d6c2ba007fd464261ae581aa258744d5b188d"
    url "https://github.com/nickooan/ntee-db/releases/download/v#{version}/nteedb-server_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "93a64325570004d3a3cbc9694e74c8840d7f8ea5dfb1d344c28fbdc931f5b4b4"
      url "https://github.com/nickooan/ntee-db/releases/download/v#{version}/nteedb-server_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "673b91bbab03de027ab972c65c3e64486c1e174b7f7c4c68fdd8f9963b4efc03"
      url "https://github.com/nickooan/ntee-db/releases/download/v#{version}/nteedb-server_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nteedb-server"
  desc "Native ntee-db server with a memcached-style text protocol"
  homepage "https://github.com/nickooan/ntee-db"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nteedb-server"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nteedb-server"]
    end
  end

  # No zap stanza required

end
