# This file was generated by GoReleaser. DO NOT EDIT.
cask "ntee" do
  version "0.4.2"

  on_macos do
    sha256 "fea77ae5e0d9e900713a8b8ac572615fae9a4f684fd458a99e5a55e790757c27"
    url "https://github.com/nickooan/ntee-editor/releases/download/v#{version}/ntee_#{version}_darwin_all.tar.gz"
  end

  name "ntee"
  desc "Terminal text editor with LSP, git diff review, and conflict solving"
  homepage "https://github.com/nickooan/ntee-editor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ntee"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ntee"]
    end
  end

  # No zap stanza required

end
